export const NT_ORIG_LANG = 'el-x-koine';
export const NT_ORIG_LANG_BIBLE = 'ugnt';
export const OT_ORIG_LANG = 'hbo';
export const OT_ORIG_LANG_BIBLE = 'uhb';

/**
 * Nested version of the books of the bible object.
 */
export const BIBLE_BOOKS = {
  oldTestament: {
    'gen': 'Genesis',
    'exo': 'Exodus',
    'lev': 'Leviticus',
    'num': 'Numbers',
    'deu': 'Deuteronomy',
    'jos': 'Joshua',
    'jdg': 'Judges',
    'rut': 'Ruth',
    '1sa': '1 Samuel',
    '2sa': '2 Samuel',
    '1ki': '1 Kings',
    '2ki': '2 Kings',
    '1ch': '1 Chronicles',
    '2ch': '2 Chronicles',
    'ezr': 'Ezra',
    'neh': 'Nehemiah',
    'est': 'Esther',
    'job': 'Job',
    'psa': 'Psalms',
    'pro': 'Proverbs',
    'ecc': 'Ecclesiastes',
    'sng': 'Song of Solomon',
    'isa': 'Isaiah',
    'jer': 'Jeremiah',
    'lam': 'Lamentations',
    'ezk': 'Ezekiel',
    'dan': 'Daniel',
    'hos': 'Hosea',
    'jol': 'Joel',
    'amo': 'Amos',
    'oba': 'Obadiah',
    'jon': 'Jonah',
    'mic': 'Micah',
    'nam': 'Nahum',
    'hab': 'Habakkuk',
    'zep': 'Zephaniah',
    'hag': 'Haggai',
    'zec': 'Zechariah',
    'mal': 'Malachi',
  },
  newTestament: {
    'mat': 'Matthew',
    'mrk': 'Mark',
    'luk': 'Luke',
    'jhn': 'John',
    'act': 'Acts',
    'rom': 'Romans',
    '1co': '1 Corinthians',
    '2co': '2 Corinthians',
    'gal': 'Galatians',
    'eph': 'Ephesians',
    'php': 'Philippians',
    'col': 'Colossians',
    '1th': '1 Thessalonians',
    '2th': '2 Thessalonians',
    '1ti': '1 Timothy',
    '2ti': '2 Timothy',
    'tit': 'Titus',
    'phm': 'Philemon',
    'heb': 'Hebrews',
    'jas': 'James',
    '1pe': '1 Peter',
    '2pe': '2 Peter',
    '1jn': '1 John',
    '2jn': '2 John',
    '3jn': '3 John',
    'jud': 'Jude',
    'rev': 'Revelation',
  },
};

export const BIBLES_ABBRV_INDEX = {
  'gen': '01',
  'exo': '02',
  'lev': '03',
  'num': '04',
  'deu': '05',
  'jos': '06',
  'jdg': '07',
  'rut': '08',
  '1sa': '09',
  '2sa': '10',
  '1ki': '11',
  '2ki': '12',
  '1ch': '13',
  '2ch': '14',
  'ezr': '15',
  'neh': '16',
  'est': '17',
  'job': '18',
  'psa': '19',
  'pro': '20',
  'ecc': '21',
  'sng': '22',
  'isa': '23',
  'jer': '24',
  'lam': '25',
  'ezk': '26',
  'dan': '27',
  'hos': '28',
  'jol': '29',
  'amo': '30',
  'oba': '31',
  'jon': '32',
  'mic': '33',
  'nam': '34',
  'hab': '35',
  'zep': '36',
  'hag': '37',
  'zec': '38',
  'mal': '39',
  'mat': '41',
  'mrk': '42',
  'luk': '43',
  'jhn': '44',
  'act': '45',
  'rom': '46',
  '1co': '47',
  '2co': '48',
  'gal': '49',
  'eph': '50',
  'php': '51',
  'col': '52',
  '1th': '53',
  '2th': '54',
  '1ti': '55',
  '2ti': '56',
  'tit': '57',
  'phm': '58',
  'heb': '59',
  'jas': '60',
  '1pe': '61',
  '2pe': '62',
  '1jn': '63',
  '2jn': '64',
  '3jn': '65',
  'jud': '66',
  'rev': '67',
};

export const ALL_BIBLE_BOOKS = {
  ...BIBLE_BOOKS.oldTestament,
  ...BIBLE_BOOKS.newTestament,
};

export const TN_FILENAMES = {
  'gen': 'ru_tn_01-GEN',
  'exo': 'ru_tn_02-EXO',
  'lev': 'ru_tn_03-LEV',
  'num': 'ru_tn_04-NUM',
  'deu': 'ru_tn_05-DEU',
  'jos': 'ru_tn_06-JOS',
  'jdg': 'ru_tn_07-JDG',
  'rut': 'ru_tn_08-RUT',
  '1sa': 'ru_tn_09-1SA',
  '2sa': 'ru_tn_10-2SA',
  '1ki': 'ru_tn_11-1KI',
  '2ki': 'ru_tn_12-2KI',
  '1ch': 'ru_tn_13-1CH',
  '2ch': 'ru_tn_14-2CH',
  'ezr': 'ru_tn_15-EZR',
  'neh': 'ru_tn_16-NEH',
  'est': 'ru_tn_17-EST',
  'job': 'ru_tn_18-JOB',
  'psa': 'ru_tn_19-PSA',
  'pro': 'ru_tn_20-PRO',
  'ecc': 'ru_tn_21-ECC',
  'sng': 'ru_tn_22-SNG',
  'isa': 'ru_tn_23-ISA',
  'jer': 'ru_tn_24-JER',
  'lam': 'ru_tn_25-LAM',
  'ezk': 'ru_tn_26-EZK',
  'dan': 'ru_tn_27-DAN',
  'hos': 'ru_tn_28-HOS',
  'jol': 'ru_tn_29-JOL',
  'amo': 'ru_tn_30-AMO',
  'oba': 'ru_tn_31-OBA',
  'jon': 'ru_tn_32-JON',
  'mic': 'ru_tn_33-MIC',
  'nam': 'ru_tn_34-NAM',
  'hab': 'ru_tn_35-HAB',
  'zep': 'ru_tn_36-ZEP',
  'hag': 'ru_tn_37-HAG',
  'zec': 'ru_tn_38-ZEC',
  'mal': 'ru_tn_39-MAL',
  'mat': 'ru_tn_41-MAT',
  'mrk': 'ru_tn_42-MRK',
  'luk': 'ru_tn_43-LUK',
  'jhn': 'ru_tn_44-JHN',
  'act': 'ru_tn_45-ACT',
  'rom': 'ru_tn_46-ROM',
  '1co': 'ru_tn_47-1CO',
  '2co': 'ru_tn_48-2CO',
  'gal': 'ru_tn_49-GAL',
  'eph': 'ru_tn_50-EPH',
  'php': 'ru_tn_51-PHP',
  'col': 'ru_tn_52-COL',
  '1th': 'ru_tn_53-1TH',
  '2th': 'ru_tn_54-2TH',
  '1ti': 'ru_tn_55-1TI',
  '2ti': 'ru_tn_56-2TI',
  'tit': 'ru_tn_57-TIT',
  'phm': 'ru_tn_58-PHM',
  'heb': 'ru_tn_59-HEB',
  'jas': 'ru_tn_60-JAS',
  '1pe': 'ru_tn_61-1PE',
  '2pe': 'ru_tn_62-2PE',
  '1jn': 'ru_tn_63-1JN',
  '2jn': 'ru_tn_64-2JN',
  '3jn': 'ru_tn_65-3JN',
  'jud': 'ru_tn_66-JUD',
  'rev': 'ru_tn_67-REV',
}
